
- name: update module description
  lineinfile: >
    dest="/etc/modules"
    group=root
    owner=root
    line="{{ item.line }}"
    state=present
    create=yes
  with_items:
    - { line: "i2c-dev" }
    - { line: "i2c-bcm2708" }
    - { line: "spi-bcm2708" }


- name: update the /boot/config.txt
  lineinfile:
    dest="/boot/config.txt"
    group=root
    owner=root
    line="{{ item.line }}"
    state=present
    create=yes
  with_items:
    - { line: "dtparam=i2c1=on" }
    - { line: "dtparam=spi=on" }
    - { line: "dtparam=i2c_arm=on" }


# reboot
